change name of the class
MordasKirill/BSUTestTask pull request #1
Opened 2020-09-02 09:27 UTC by MordasKirill

1) test task 1-6 done

2020-09-02 09:30 UTC, tatsiana-mordas requested changes

2020-09-02 09:30 UTC, tatsiana-mordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
>      private static void firstTask(){
Make method reusable for different input parameters. add appropriate return parameter and input params

2020-09-04 18:48 UTC, tatsiana-mordas requested changes

2020-09-04 18:48 UTC, tatsiana-mordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double firstVariableTask2 = (Math.random() * 20 - 10);
а в первой лекции случайно не упоминалось ничего про Random random = new Random();? только про Math.random()?

2020-09-04 18:48 UTC, tatsiana-mordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = (firstVariable * 1000) % 1000 + (int) firstVariable / 1000.0;
не уверена что именно такой способ решения задачи ожидают 4 таске. Может в лекции было что то про BigDecimal? тогда примерно можно глянуть способ решения здесь https://www.baeldung.com/java-separate-double-into-integer-decimal-parts часть 4.
Если нет, то наверное можно и такое решение оставить только разбебей выржение на 2 части для читабельности: 1. значение до запятой и 2.после запятой

2020-09-09 12:00 UTC, AlekseiMordas requested changes

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = (Math.sin(firstVariable) + Math.cos(secondVariable) / Math.cos(firstVariable) - Math.sin(secondVariable))
Не правильная формула. Проверь все руками, прежде чем я буду опять в это погружаться. Формула должна быть проверена и посчитана тобой лично.

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = (Math.sin(firstVariable) + Math.cos(secondVariable) / Math.cos(firstVariable) - Math.sin(secondVariable))
Когда пофиксишь-оставь комент

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = (( secondVariable + sqrt) / 2 * firstVariable) - Math.pow(firstVariable, 3) * thirdVariable + (1 / Math.pow(secondVariable, 2));
Не правильная формула

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +    private static String functionForTheFirstTask(double firstAngle, double secondAngle) {
я не понимаю название метода. Что он делает?

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        return "It is a triangle " + isTriangleReal + " this triangle is rectangular " + isTriangleRectangular;
Если рещультат метода ответ на вопрос треуголтник это или нет  - он должен вернуть true/false.
Далее, нет проверки на отрицательные и нулевые числа.

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        secondMin = Math.min(thirdVariable, fourthVariable);
строчки 72,73 - сократить. int firstMin =  Math.min(firstVariable, secondVariable);

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +    private static String  functionForTheTaskTree( int x1, int y1, int x2, int y2, int x3, int y3){
Назвние опять не ясное

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +    }
Впервые вижу такое доказательство. Ты это сам придумал?

2020-09-09 12:00 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        if (((A < x)&&(B < y))||((A < x) && (B < z))||((A < z) && (B < y))){
Укажи ссылку на матетическое док-во формулы. У меня есть большие сомнения что она правильная

2020-09-09 12:16 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +    }
https://qna.habr.com/q/217987

2020-09-11 19:42 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        if (((A < x)&&(B < y))||((A < x) && (B < z))||((A < z) && (B < y))){
fixed

2020-09-11 19:42 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +    }
fixed

2020-09-11 19:42 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +    private static String  functionForTheTaskTree( int x1, int y1, int x2, int y2, int x3, int y3){
fixed

2020-09-11 19:42 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        secondMin = Math.min(thirdVariable, fourthVariable);
fixed

2020-09-11 19:43 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +    private static String functionForTheFirstTask(double firstAngle, double secondAngle) {
fixed

2020-09-12 15:18 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = (( secondVariable + sqrt) / 2 * firstVariable) - Math.pow(firstVariable, 3) * thirdVariable + (1 / Math.pow(secondVariable, 2));
fixed

2020-09-12 15:18 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = (Math.sin(firstVariable) + Math.cos(secondVariable) / Math.cos(firstVariable) - Math.sin(secondVariable))
fixed

2020-09-14 20:37 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = ((sin(firstVariable) + cos(secondVariable)) / (cos(firstVariable) - sin(secondVariable))) * (tan(firstVariable * secondVariable));
вместо присвоения double result сделай просто return ((sin...

2020-09-14 20:37 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        return (int) Math.round(result);
почему возвращаемое значение double, а приведение типа к int?

2020-09-14 20:37 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = ((firstVariable - 3) * secondVariable / 2) + thirdVariable;
сделйа просто return

2020-09-14 20:37 UTC, AlekseiMordas commented on src/branching/Branching.java
> +public class Branching {
Касается каждого класса:
Сложно читать код, потому что я вынужден искать main метод. Он должен быть выше всех методов.

2020-09-14 20:37 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = beforePoint + afterPoint;
просто return

2020-09-14 20:37 UTC, AlekseiMordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        //1 random input variables introduced for the first tusk as an example
task пишется через  a!

2020-09-14 20:37 UTC, AlekseiMordas commented on src/cycles/Cycles.java
> +        for (int i = 1; i <= 20; i++) {
первый двухсот чисел (200)

2020-09-14 21:05 UTC, MordasKirill commented on src/cycles/Cycles.java
> +        for (int i = 1; i <= 20; i++) {
Тут я ещё ошибочку нашёл, убрал "+" перед =

2020-09-14 21:09 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        //1 random input variables introduced for the first tusk as an example
Поправил

2020-09-14 21:10 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = beforePoint + afterPoint;
поправил

2020-09-14 21:10 UTC, MordasKirill commented on src/branching/Branching.java
> +public class Branching {
поправил

2020-09-14 21:10 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = ((firstVariable - 3) * secondVariable / 2) + thirdVariable;
поправил

2020-09-14 21:10 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        return (int) Math.round(result);
поправил

2020-09-14 21:10 UTC, MordasKirill commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +        double result = ((sin(firstVariable) + cos(secondVariable)) / (cos(firstVariable) - sin(secondVariable))) * (tan(firstVariable * secondVariable));
поправил

2020-09-15 10:35 UTC, tatsiana-mordas requested changes

2020-09-15 10:35 UTC, tatsiana-mordas commented on src/com/softwareDevelopment/runner/LinearPrograms.java
> +    }
Почти правильно)) но Замени на решение
private static boolean calculateFunctionForTheTaskNumberSix(int x, int y) {
return (y=>0 && y<4 && x>-2 && x<2) || (y<0 && y>-3 && x>-4 && x<4);
}

2020-09-15 10:35 UTC, tatsiana-mordas commented on src/cycles/Cycles.java
> +        //Я не уверен, что уловил суть задания, но вроде так
такие комменты только в пул реквесте оставляй для нас) удали его

2020-09-15 10:35 UTC, tatsiana-mordas commented on src/cycles/Cycles.java
> +    private static void calculateFunctionForTheSecondTask(int A, int B, double h, int x) {
названия переменных с маленькой буквы

2020-09-15 10:35 UTC, tatsiana-mordas commented on src/cycles/Cycles.java
> +    private static void calculateFunctionForTheTaskEight(String firstVariable, String secondVariable){
remove lines 82-88

2020-09-15 10:35 UTC, tatsiana-mordas commented on src/cycles/Cycles.java
> +        char charsSigns = '\u0000';
звмени '\u0000' на Character.MIN_VALUE, это тоже самое
char charsSigns = Character.MIN_VALUE;

2020-09-15 10:35 UTC, tatsiana-mordas commented on src/cycles/Cycles.java
> +        for (int i = 0; i <= 10000; i++) {
Замени 1000 на Character.MAX_VALUE :
for (int i = charsSigns; i <= Character.MAX_VALUE; i++) {

2020-09-15 10:35 UTC, tatsiana-mordas commented on src/cycles/Cycles.java
> +    private static void calculateFunctionForTheTaskFive(double e){
этот метод явно должен сумму возвращать

2020-10-01 09:17 UTC, AlekseiMordas approved these changes

2020-10-01 09:18 UTC, AlekseiMordas approved these changes

2020-10-01 09:27 UTC, tatsiana-mordas approved these changes

2020-10-28 17:22 UTC, merged