Test task 2
MordasKirill/BSUTestTask pull request #2
Opened 2020-10-01 14:50 UTC by MordasKirill

That is a pull request for lesson 2

2020-10-01 18:55 UTC, tatsiana-mordas requested changes

2020-10-01 18:55 UTC, tatsiana-mordas commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        nextPrime:
в общем переделай без использования "nextPrime:"

2020-10-01 18:55 UTC, tatsiana-mordas commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +    }
1. Зачем ты на вход в методе  передаешь int n? если это количество элементов в массиве firstArray, можем ли мы прямо в методе узнать чему равен n?
2. все if, else, for блоки должны быть с фигурными скобками, джава позволяет писать код и без них, но это плохая практика, поэтому привыкай, и исправь везде похожие ошибки: т.е должно быть так: 
 for (int tmpEl : firstArray) { 
minVal = Math.min(minVal, tmpEl); 
}
3. мне не нравится нейминг, tmpEl - а имеенно хвостик tmp, уж лучше просто оставить "el" или "element"
4. строки 182-186 "countMinElem" - а не проще ли расчитать не количество  минимальных элементов в массиве, а уже размер финального массива без учета мин элементов, чтоб не пришлось потом делать подобных расчетов new int[n - countMinElem]; в строке 186. PS это решается всего лишь знаком != в 184 строке.
5. Верни в методе  secondArray, это будет логично, т.к в задаче тебя явно просят сформировать новый массив

2020-10-01 18:55 UTC, tatsiana-mordas commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        task11();
task 11 явно не в этом классе должен быть

2020-10-08 19:16 UTC, MordasKirill commented on src/com/software_development/lesson2/ArraysOfArrays.java
> +    }
исправлено

2020-10-08 19:16 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +    }
исправлено

2020-10-08 19:17 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        //1 random input variable introduced for the first task as an example
исправлено

2020-10-08 19:17 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +    }
исправлено

2020-10-08 19:17 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        int positiveNumbers = 0, negativeNumbers = 0, zero = 0;
исправлено

2020-10-08 19:17 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        array[maxi] = array[maxi]-array[mini];
в процессе...

2020-10-08 19:17 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +    }
исправлено

2020-10-08 19:18 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        nextPrime:
исправлено, но частично, есть пока проблемы

2020-10-08 19:18 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +    }
исправлено

2020-10-08 19:18 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        task11();
исправлено

2020-10-08 19:21 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        }
исправлено

2020-10-08 19:21 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        else if (array[i]==0){
исправлено

2020-10-08 19:22 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        int maxi = 0;
исправлено

2020-10-08 19:22 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +            throw new IllegalArgumentException("nothing to swap");
исправлено

2020-10-08 19:40 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +    }
Про K не заметил, уже поправил, в следующем коммите будет правка

2020-10-08 19:52 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +    }
1й и 3й пункты не заметил, исправлю...

2020-10-15 08:33 UTC, AlekseiMordas commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        array[maxi] = array[maxi]-array[mini];
TODO

2020-10-15 13:09 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        array[maxi] = array[maxi]-array[mini];
fixed

2020-10-15 13:12 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +        nextPrime:
исправлено полностью

2020-10-15 13:13 UTC, MordasKirill commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +    }
исправлено полностью

2020-10-17 07:58 UTC, AlekseiMordas requested changes

2020-10-17 07:58 UTC, AlekseiMordas commented on src/com/software_development/lesson2/OneDimensionalArrays.java
> +            firstArray[i] = rand.nextInt(20) - 10;
Здесь ты использовал 2 разных рандома.
Math.Random и new Random().nextInt()
я бы использовал что-то одно

2020-10-19 07:42 UTC, AlekseiMordas requested changes

2020-10-19 07:42 UTC, AlekseiMordas commented on src/com/software_development/lesson2/OneDimensionalArraysAndSorts.java
> +        unionOfArraysTask1(firstArrayLength, secondArrayLength, k);
Что означает переменная k?

2020-10-19 07:42 UTC, AlekseiMordas commented on src/com/software_development/lesson2/OneDimensionalArraysAndSorts.java
> +    private static void nonDecreasingSequenceTask2(int n, int m){
что значит n,m?

2020-10-19 07:42 UTC, AlekseiMordas commented on src/com/software_development/lesson2/OneDimensionalArraysAndSorts.java
> +    private static void selectionSortTask3(int n){
что такое n

2020-10-20 18:00 UTC, AlekseiMordas approved these changes

2020-10-27 08:30 UTC, AlekseiMordas requested changes
В целом отлично, поправь пару замечаний и мы двинемся дальше :)

2020-10-27 08:30 UTC, AlekseiMordas commented on src/com/software_development/lesson2/DecompositionUsingMethods.java
> +        double a = scannerForTask3.nextInt();
я не понимаю что такое a

2020-10-27 08:30 UTC, AlekseiMordas commented on src/com/software_development/lesson2/DecompositionUsingMethods.java
> +    private static boolean isMutuallyTask6 (int[] a) {
снова ошибка. ВСЕ переменные, должны быть понятно названы. Если в условие не указано название этих переменных аля x и y

2020-10-27 08:30 UTC, AlekseiMordas commented on src/com/software_development/lesson2/DecompositionUsingMethods.java
> +    private static double maxDistance;
почему эта переменная объявлена глобально а не в методе

2020-10-27 08:30 UTC, AlekseiMordas commented on src/com/software_development/lesson2/DecompositionUsingMethods.java
> +        System.out.println(moreDigitsTask11(firstVariableTask11, secondVariableTask11));
хорошее решение, для интов еще можно было сдлеать firstVariableTask11.toString().lenght() - получишь кол-во цифр) Но с логарифомом тоже отлично

2020-10-27 12:56 UTC, MordasKirill commented on src/com/software_development/lesson2/DecompositionUsingMethods.java
> +    private static double maxDistance;
Потому что она используется как в методе, так и в мэйне

2020-10-27 12:56 UTC, MordasKirill commented on src/com/software_development/lesson2/DecompositionUsingMethods.java
> +    private static boolean isMutuallyTask6 (int[] a) {
fixed

2020-10-27 12:56 UTC, MordasKirill commented on src/com/software_development/lesson2/DecompositionUsingMethods.java
> +        double a = scannerForTask3.nextInt();
fixed

2020-10-28 17:20 UTC, AlekseiMordas approved these changes

2020-10-28 17:22 UTC, merged