Test task 3
MordasKirill/BSUTestTask pull request #3
Opened 2020-11-03 11:30 UTC by MordasKirill

That is a pull request for lesson 3

2020-11-04 17:23 UTC, AlekseiMordas approved these changes

2020-11-04 17:23 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAndStringBuilder.java
> +        for (int i = 1; i < words.length; i++) {
https://www.geeksforgeeks.org/difference-between-length-of-array-and-size-of-arraylist-in-java/#:~:text=Array%20has%20length%20property%20which,the%20Array%20or%20Array%20object.&text=The%20java%20ArrayList%20has%20size,to%20find%20size%20of%20ArrayList.
продебаж что тебе возвращает length. Он не вернет кол-во слов, а вернет кол-во символов

2020-11-04 17:23 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAndStringBuilder.java
> +    private static int amountOfSpacesTask1(String strings) {
неправильное название метода. В основном если метод что то возвращает он начинается с get
getMaxAmount....

2020-11-04 17:23 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAndStringBuilder.java
> +        for (int i = 0; i < strings.length(); i++) {
мне кажется здесь алгорим не верный. В задачке хотят найти максимальное кол-во пробелов которые идут подряд.Точно работает?

2020-11-04 17:23 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAndStringBuilder.java
> +        }
Мне кажется это можно сделать в 1 for

2020-11-04 17:38 UTC, AlekseiMordas requested changes

2020-11-04 17:38 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +        System.out.println(stringTask2.replace("word", "letter"));
Очень сложное решение
Используй replaceAll

2020-11-04 17:38 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +        System.out.println("The quantity of digits is: " + counter);
Все уже написано до нас.
Character.isDigit()

2020-11-04 17:38 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +                if (i == strings.length() - 1 || !isDigitTask4(strings.charAt(i + 1))) {
А зачем это условие? если мы убедились что текущий char это цифра, то сделали counter++ и все.

2020-11-04 17:38 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +        return strBuilder.toString();
Я не запускал алгоритм, но похоже ты не учитваешь повторяющийся пробел.(см условие)
Как я вижу мы находим первый пробел, если след char  пробел - удаляем, и так пока не встретим не пробел.
И так до той поры пока не перестанем находить вхождение пробела.

2020-11-08 17:33 UTC, MordasKirill commented on src/com/software_development/lesson3/StringAndStringBuilder.java
> +        for (int i = 1; i < words.length; i++) {
Этот метод и должен возвращать кол-во символов, т.к этот метод ищет самое большое слово

2020-11-08 17:35 UTC, MordasKirill commented on src/com/software_development/lesson3/StringAndStringBuilder.java
> +    private static int amountOfSpacesTask1(String strings) {
исправлено

2020-11-08 17:46 UTC, MordasKirill commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +        System.out.println("The quantity of digits is: " + counter);
Исправлено

2020-11-08 17:51 UTC, MordasKirill commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +                if (i == strings.length() - 1 || !isDigitTask4(strings.charAt(i + 1))) {
Логично, исправлено

2020-11-08 17:59 UTC, MordasKirill commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +        System.out.println(stringTask2.replace("word", "letter"));
Исправлено

2020-11-08 18:19 UTC, MordasKirill commented on src/com/software_development/lesson3/StringAndStringBuilder.java
> +        }
Не получилось..

2020-11-08 18:41 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAndStringBuilder.java
> +        for (int i = 1; i < words.length; i++) {
Посмотри сколько символов возвращает words.length

2020-11-09 12:23 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +        return strBuilder.toString();
Нужно сделать эту задачу самостоятельно.
Удали алгоритм м начни писать с нуля.

2020-11-09 19:52 UTC, AlekseiMordas commented on src/com/software_development/lesson3/StringAsCharacterArray.java
> +                if (stringBuilder.charAt(i+1) == ' '){
молодец, это решение мне нравится

2020-11-10 17:36 UTC, merged